group: management
apiVersion: v1alpha1
kind: CredentialRequestDefinition
name: password
metadata:
  scope:
    kind: Environment
    name: resource-assets-env
spec:
  schema:
    $schema: "http://json-schema.org/draft-07/schema#"
    type: object
    properties:
      name:
        type: string
        title: "Name"
        description: Your name is required for provisioning a credential.        
  provision:
    schema:
      $schema: "http://json-schema.org/draft-07/schema#"
      type: object
      description: Provisioned password based credential
      properties:
        password:
          type: string
          title: Password
          description: Your password.
          x-axway-label: Password
          x-axway-encrypted: true