group: management
apiVersion: v1alpha1
kind: AccessRequestDefinition
name: acc-req-def
metadata:
  scope:
    kind: Environment
    name: resource-assets-env
spec:
  schema: 
    $schema: "http://json-schema.org/draft-07/schema#"
    type: object
    properties: {}