group: catalog
apiVersion: v1
kind: Quota
name: freemium-quota
metadata:
  scope:
    kind: ProductPlan
    name: freemium
spec:
  unit: transactions
  resources:
    - kind: AssetResource
      name: musicalinstruments-1.0.0/resource-assets-env-musicalinstruments
  pricing:
    type: fixed
    interval: monthly
    limit: 
      type: strict
      value: 10000